= Demo App - *Soluciones*

A continuación se incluyen algunas pistas y las soluciones al reto *Demo App*.

== Abrir DevSpaces

Revisar la sección: **2. Entorno** > **IDE web**.

== Ejecutar y Corregir tests

[tabs, subs="attributes+,+macros"]	
====	
Guía::	
+	
--	
* Dentro del IDE: ``[MENU] > Terminal > Run Task``.
* Seleccionar ``devfile`` y ejecutar ``1. Run unit tests``.
* Revisar los logs y corregir el error.

TIP: Es posible que falte algun campo por actualizar en el método ``update``?.

--	
Solución::	
+	
--	
* Dentro del IDE: ``[MENU] > Terminal > Run Task``.
* Seleccionar ``devfile`` y ejecutar ``1. Run unit tests``.
* Revisar los logs y corregir el error.
* Abrir la clase ``BankAccountController`` y moficar el método ``update``:

[.console-input]
[source,java,subs="attributes+,+macros"]	
----	
@PutMapping("/{id}")
public ResponseEntity<BankAccount> update(@PathVariable Long id, @RequestBody BankAccount updated) {
return repository.findById(id)
    .map(acc -> {
        acc.setOwner(updated.getOwner()); // <- Corregido!
        acc.setBalance(updated.getBalance());
        repository.save(acc);
        return ResponseEntity.ok(acc);
    })
    .orElse(ResponseEntity.notFound().build());
}
----	
* Volver a ejecutar los tests para validar.
====

== Ejecutar en local

Una vez corregida la aplicación realizar los siguientes pasos:

* Dentro del IDE: ``[MENU] > Terminal > Run Task``.
* Seleccionar ``devfile`` y ejecutar ``3. Run application locally``.
* Esperar a que arranque y cuando salga una ventana diciendo ``Process accounts-index is now listening on port 8080. Open it ?`` pulsar ``Open in New Tab``.
* Realizar algunos tests en la web.

CAUTION: Si el navegador automaticamente usa **https**, cambiarlo a **http** para poder acceder a la aplicacion.

== Subir a Git

Existen dos opciones:

* Utilizar el menu de **Git** de visual estudio para hacer commit y push.
* Dentro del IDE: ``[MENU] > Terminal > New Terminal``. En la nueva terminal:

[.console-input]
[source,bash,subs="attributes+,+macros"]	
----	
git status
git add .
git commit -m "fixed tests"
git push
----	

* Usar los credenciales descritos en la seccion **2. Entorno**.