= Bienvenidos al **Hackathon** de OpenShift
:page-layout: home
:!sectids:
ifndef::lab[]
:lab-name: Java
endif::[]

Bienvenido al Hackathon de OpenShift: **Desplegando una aplicaci칩n en OpenShift**

춰Nos alegra contar con tu participaci칩n en este workathon!

춰Esperamos que disfrutes de la experiencia y que este workathon te ayude a sentirte m치s c칩modo y aut칩nomo en entornos cloud-native y Kubernetes!

**춰Manos a la obra! 游**

== Introducci칩n

A lo largo de esta jornada, vas a trabajar de forma pr치ctica y colaborativa en el ciclo completo de desarrollo, despliegue y mejora de una aplicaci칩n Java SpringBoot en un entorno Kubernetes.

El objetivo es que experimentes de primera mano c칩mo es el flujo de trabajo en este tipo de entornos, desde la revisi칩n y modificaci칩n del c칩digo en un entorno conterizado, hasta la configuracion y el despliegue a trav칠s de GitOps.

== 쯈u칠 te vas a encontrar en esta gu칤a?

* Accesos y recursos: Aqu칤 encontrar치s todos los enlaces, credenciales e instrucciones necesarias para acceder a las distintas plataformas y recursos que usar치s durante el workathon.
* Entorno preconfigurado: Para facilitar la experiencia, podr치s trabajar en OpenShift usando DevSpaces, evitando as칤 complicaciones de configuraci칩n local.
* Pasos guiados: El itinerario est치 dividido en bloques, de modo que podr치s avanzar paso a paso, probando y desplegando una aplicaci칩n real y enfrent치ndote a peque침os retos t칠cnicos.
* Retos extra: Si quieres profundizar a칰n m치s, encontrar치s una secci칩n de retos adicionales para llevar la aplicaci칩n al siguiente nivel.

== 쮺칩mo funciona el workathon?
* Reto: Se plantearan varios retos en los que inicialmente no se dar치 ning칰n tipo de gu칤a o pista.
* Gu칤a paso a paso: Cada reto contiene un apartado *-soluciones donde encontrar치s o bien unas guias que te pueden ayudar o directamente la soluci칩n.
* Soporte: Si te atascas, encontrar치s pistas y, si lo necesitas, las soluciones completas. Lo importante es que aprendas experimentando y compartiendo dudas con el grupo.
* Retos adaptables: Los retos extra son opcionales, pensados para quienes quieran un desaf칤o mayor o profundizar en aspectos clave como configuraci칩n avanzada, despliegue automatizado o seguridad.

== 쯈u칠 aprender치s?
* A colaborar y gestionar c칩digo fuente con Gitea/Git.
* A trabajar en un entorno Kubernetes sin necesidad de instalaciones locales, gracias a DevSpaces y el web terminal.
* A desplegar y gestionar aplicaciones y bases de datos en OpenShift.
* A descubrir la potencia de ArgoCD para despliegue continuo.
* A configurar aplicaciones para entornos productivos usando configMaps, secrets, health checks y gesti칩n de recursos.


