---
- name: Uninstallation
  hosts: localhost
  gather_facts: false

  vars_prompt:
    - name: "max_users_input"
      prompt: "How many users were configured for the hackathon?"
      private: no

  tasks:

    - name: Convert number of users to int
      ansible.builtin.set_fact:
        max_users: "{{ max_users_input | int }}"

    - name: Setup kubeconfig file
      ansible.builtin.include_role:
        name: demos.utils.kubeconfig

    - name: Remove Gitea Namespace
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: project.openshift.io/v1
          kind: Project
          metadata:
            name: gitea
      failed_when: false  # In case it was already deleted

    - name: Wait until Gitea project is fully deleted
      command: oc get project gitea
      register: project_check
      failed_when: false
      retries: 60
      delay: 10
      until: project_check.rc != 0

    - name: Delete demo-app namespaces
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Namespace
        name: "{{ item }}"
      loop: "{{ query('sequence', 'start=1 end=' + max_users|string + ' format=user-%d-app') + ['admin-app'] }}"

    - name: Delete demo-argo namespaces
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Namespace
        name: "{{ item }}"
      loop: "{{ query('sequence', 'start=1 end=' + max_users|string + ' format=user-%d-argo')}}"

    - name: Delete demo-argo-db namespaces
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Namespace
        name: "{{ item }}"
      loop: "{{ query('sequence', 'start=1 end=' + max_users|string + ' format=user-%d-argo-db') + ['admin-app-db'] }}"

    - name: Delete HTPASSWD
      ansible.builtin.include_role:
        name: demos.utils.htpasswd_provider
      vars:
        htpasswd_provider_operation: uninstall
        htpasswd_provider:
          name: ocp-hackathon

  vars_files:
    - vars.yaml
