version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel9:latest

dependencies:
  galaxy:
    collections:
      - name: community.general
      - name: https://github.com/zaskan/demos.utils.git
        type: git
        version: 1.0.4
      - name: kubernetes.core
      

additional_build_steps:
  prepend_base:
    - RUN microdnf install -y tar gzip python3-pip httpd-tools && pip3 install passlib && curl -fsSL https://get.helm.sh/helm-v3.14.4-linux-amd64.tar.gz -o helm.tar.gz && tar -zxvf helm.tar.gz && mv linux-amd64/helm /usr/local/bin/helm && chmod +x /usr/local/bin/helm && rm -rf linux-amd64 helm.tar.gz && microdnf clean all


options:
  package_manager_path: /usr/bin/microdnf